// demo/solid/src/main.tsx
import { render } from "solid-js/web";
import "@pixel-loader/core";

function App() {
  return (
    <div
      style={{
        display: "flex",
        "align-items": "center",
        "justify-content": "center",
        "min-height": "100vh",
        "flex-direction": "column",
        gap: "2rem",
      }}
    >
      <h1>PixelLoader Solid Demo</h1>
      <pixel-loader color="#3b82f6" preset="wave-lr" size="48" />
    </div>
  );
}

const rootElement = document.getElementById("root");
if (rootElement) {
  render(() => <App />, rootElement);
}

// demo/react/src/main.tsx
import { PixelLoader } from "@pixel-loader/react";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

function App() {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "100vh",
        flexDirection: "column",
        gap: "2rem",
      }}
    >
      <h1>PixelLoader React Demo</h1>
      <PixelLoader color="#3b82f6" preset="wave-lr" size={48} />
    </div>
  );
}

const rootElement = document.getElementById("root");
if (rootElement) {
  createRoot(rootElement).render(
    <StrictMode>
      <App />
    </StrictMode>
  );
}
